### PR TITLE
Add the ability to change the default port

### PR DESCRIPTION
**Pull request by THPubs**
Now people can use the flag `-p` or `--port` to define their port. The script will also update the database's `siteurl` and `home` according to the new port to prevent WordPress from re-directing to the old port.

Also added the alias `s` to `serve` for lazy people like me :wink: and colored the errors in red.

Solves #15 

Hope you like the changes :smile:

### CODE REVIEW

**Comment by kasunben** [comment]
@THPubs Wow! Great 👍 Will merge this.

**Comment by THPubs** [comment]
@thinkholic Cool! Thanks :smile:

**Comment by kasunben** [comment]
@THPubs 

> Something not directly related to the PR.

Just published a node wrapper for `WP-CLI` and hoping to integrate it with this.
See:
https://github.com/kodeflex/node-wp-cli

Plus, hoping to change the project name as `wp-artisan`. Any opinion? :)

**Comment by THPubs** [comment]
The idea of the node wrapper is cool. I like it :-)

The name is also good but one small concern... `artisan` is a good name but, some people might find it hard to remember or might misspell it because it's not a common word. What do you think?

**Comment by THPubs** [comment]
Ah looks like you have already re-named :smile: Anyway I do like the name. Do I have to make a new pull request to the new project?

**Comment by kasunben** [comment]
> Ah looks like you have already re-named 😄 Anyway I do like the name. Do I have to make a new pull request to the new project?

No nop. Still considering, anyway I reserved the namespace. If you have a suggestion let's discuss. Actually I too have some concerns. Name is cool, but remembering is kinda hard like you told. Plus, there is a website with that name too. :/

**Comment by THPubs** [comment]
Ahaa then it's a problem. I'll also think and see :smile:

**Pull request merged**
